### PR TITLE
Separate media configuration and M8 publication from the `msaf-configuration` app

### PR DESCRIPTION
**Pull request by davidjwbbc**
# Introduction

The current situation, as discussed in [discussion#43](https://github.com/5G-MAG/rt-5gms-application-provider/discussions/43#discussion-6846658), is that the `msaf-configuration` python tool is the only part of this application provider implementation that can publish files for distribution via interface M8. To support this the `msaf-configuration` tool also implements a media data model that allows it to hold extra media entry points that are only published via M8.

This PR implements the separation of this data model and the M8 publication from the `msaf-configuration` tool and moves these operations into some new python modules that can then be re-used by other application provider tools that change the model and ideally need to publish M8 files.

This implements issue #48.

# Description

This PR introduces two new python modules, `rt_media_configuration` which provides the extended model, and `rt_m8_output` which provides the M8 publication classes.

## `rt_media_configuration`

The `rt_media_configuration` Python module contains the classes that model a media configuration. The top level class is `MediaConfiguration`. A `MediaConfiguration` object can store a media configuration model and then may synchronise this model with the configuration on a running 5GMS Application Function. The module also provides a sub-module, `rt_media_configuration.importers`, for importing configuration from various sources into a `MediaConfiguration`.

The following is a diagram of the model implemented by this PR

```mermaid
classDiagram
    class MediaConfiguration{
        +str asp_id
        +str serialise(bool pretty=False)
        +reset()
        +bool restoreModel()
        +MediaSession newMediaSession(*args, **kwargs)
        +bool addMediaSession(MediaSession session)
        +bool removeMediaSession(str session_id=None, MediaSession entry=None)
        +iter mediaSessions()
        +MediaSession mediaSessionById(str session_id)
        +synchronise()
        +list deltas(MediaConfiguration other)
    }
    class MediaSession{
        +bool is_downlink
        +str external_app_id
        +str asp_id
        +dict[str->MediaServerCertificate] certificates
        +MediaEntry media_entry
        +MediaReportingConfiguration reporting_configurations
        +dict[str->MediaDynamicPolicy] dynamic_policies
        +bool shallow_eq(MediaSession other)
        +str serialise(bool pretty=False)
        MediaSession deserialise(str json_string)$
        MediaSession fromJSONObject(dict object)$
        +dict jsonObject()
        +str identity()
        +addCertificate(MediaServerCertificate cert)
        +bool removeCertificate(str ident=None, MediaServerCertificate certificate=None)
        +MediaServerCertificate certificateByCertId(str ident)
        +MediaServerCertificate certificateByLocalId(str ident)
        +MediaServerCertificate certificateByIdent(str ident)
        +setConsumptionReportingConfiguration(MediaConsumptionReportingConfiguration config)
        +unsetConsumptionReportingConfiguration()
        +addMetricsReportingConfiguration(MediaMetricsReportingConfiguration config)
        +bool removeMetricsReportingConfiguration(MediaMetricsReportingConfiguration config)
        +unsetMetricsReportingConfigurations()
        +addDynamicPolicy(str external_reference, MediaDynamicPolicy policy)
        +removeDynamicPolicy(str external_reference)
        +unsetDynamicPolicies()
    }
    class MediaEntry{
        +str name
        +str ingest_url_prefix
        +bool is_pull
        +list[MediaDistribution] distributions
        +list[MediaAppDistribution] app_distributions
    }
    class MediaDistribution{
        +str domain_name_alias
        +str certificate_id
        +MediaEntryPoint entry_point
    }
    class MediaAppDistribution{
        +str name
        +list[MediaEntryPoint] entry_points
    }
    class MediaEntryPoint{
        +str relative_url
        +str content_type
        +list[str] profiles
    }
    class MediaServerCertificate{
        +str id
        +str certificate_id
        +list[str] domain_names
        +str public_cert
    }
    class MediaReportingConfiguration{
        +MediaConsumptionReportingConfiguration consumption
        +list[MediaMetricsReportingConfiguration] metrics
    }
    class MediaConsumptionReportingConfiguration{
        +int reporting_interval
        +float sample_percentage
        +bool location_reporting
        +bool access_reporting
    }
    class MediaMetricsReportingConfiguration{
        +int sampling_period
        +str metrics_reporting_configuration_id
        +list[Snssai] slice_scope
        +str scheme
        +str data_network_name
        +int reporting_interval
        +float sample_percentage
        +list[str] url_filters
        +list[str] metrics
    }
    class MediaDynamicPolicy{
        +str id
        +str policy_template_id
        +MediaDynamicPolicySessionContext session_context
        +MediaQoSParameters qos_parameters
        +MediaChargingSpecification charging
    }
    class MediaDynamicPolicySessionContext{
        +Snssai snssai
        +str dnn
    }
    class MediaQoSParameters{
        +str reference
        +Bitrate max_auth_bitrate_uplink
        +Bitrate max_auth_bitrate_downlink
        +int default_packet_loss_rate_uplink
        +int default_packet_loss_rate_downlink
    }
    class MediaChargingSpecification{
        +str sponsor_id
        +bool enabled
        +list[Gpsi] gpsis
    }
    class Snssai{
        +int sst
        +str sd
    }
    class Bitrate{
    }
    class Gpsi{
    }
    MediaConfiguration "1" *-- "*" MediaSession
    MediaSession "1" *-- "*" MediaServerCertificate
    MediaSession "1" *-- "0..1" MediaEntry
    MediaSession "1" *-- "0..1" MediaReportingConfiguration
    MediaSession "1" *-- "*" MediaDynamicPolicy
    MediaEntry "1" *-- "1..*" MediaDistribution
    MediaEntry "1" *-- "*" MediaAppDistribution
    MediaDistribution "1" *-- "0..1" MediaEntryPoint
    MediaServerCertificate "1" <-- "*" MediaDistribution
    MediaAppDistribution "1" *-- "1..*" MediaEntryPoint
    MediaReportingConfiguration "1" *-- "0..1" MediaConsumptionReportingConfiguration
    MediaReportingConfiguration "1" *-- "*" MediaMetricsReportingConfiguration
    MediaMetricsReportingConfiguration "1" *-- "0..1" Snssai
    MediaDynamicPolicy "1" *-- "0..1" MediaDynamicPolicySessionContext
    MediaDynamicPolicy "1" *-- "0..1" MediaQoSParameters
    MediaDynamicPolicy "1" *-- "0..1" MediaChargingSpecification
    MediaDynamicPolicySessionContext "1" *-- "0..1" Snssai
    MediaQoSParameters "1" *-- "0..2" Bitrate
    MediaChargingSpecification "1" *-- "*" Gpsi
    Bitrate <|-- str
    Gpsi <|-- str
```

The `MediaConfiguration` object holds a configuration model in memory and when the `synchronise()` method is called it pushes the configuration to a running 5GMS AF using the `rt_m1_client.M1Session` class. The `deltas()` method can be used to get a list of change operations that should be applied to the current `MediaConfiguration` to transform it into the provided `MediaConfiguration` and apply those changes, via an `rt_m1_client.M1Session` object, to a running 5GMS AF.

This means that the current job of the `msaf-configuration` tool can be done by:
1. Using `rt_media_configuration.importers.M1SessionImporter` to get the current configuration from the 5GMS AF and configure a `MediaConfiguration` object.
2. Using `rt_media_configuration.importers.StreamsJSONImporter` to load a `streams.json` file into another `MediaConfiguration` object.
3. Get the changes by asking for the `deltas()` from the M1Session imported `MediaConfiguration` to transform it into the `streams.json` `MediaConfiguration`
4. Apply the list of deltas.

Alternatively, more simply by:
1. Using `rt_media_configuration.importers.StreamsJSONImporter` to load a `streams.json` file into a `MediaConfiguration` object.
2. Calling the `synchronise()` method on the `MediaConfiguration` object.
    - This method uses the `M1SessionImporter` to load the current configuration, gets the deltas between that and the current  `MediaConfiguration` object, and then applies the deltas.

### `rt_media_configuration.importers`

This Python module implements 2 configuration importer classes, `StreamsJSONImporter` and `M1SessionImporter`.

A `StreamsJSONImporter` object is initialised with the file path of a 5G-MAG `streams.json` file (as currently used by the `msaf-configuration` tool) and can import the configuration model from the file into a `MediaConfiguration` object.

The `M1SessionImporter` is initialised with information for connecting to a running 5GMS AF and a persistent data store and imports the current configuration of the AF into a MediaConfiguration object.

### CODE REVIEW

**Comment by davidjwbbc** [comment]
Note this work is not finished yet, but is significantly far enough along for others to start looking at it and should hopefully unblock the WebUI and m1-session update issues.

Still needed:
- M8 publication implementation
- Fixes for delta production (maybe some incorrect comparisons; implementation of the extra configuration storage in the persistent data store, during synchronisation, so that it can be reapplied to the 5GMS AF configuration on import).

**Review by stojkovicv — DISMISSED** [review]
This seems good to be merged.

**Review by jordijoangimenez — DISMISSED** [review]
Decision to merge. Fine-tuning will be provided by @stojkovicv with a new PR

**Review by jordijoangimenez — APPROVED** [review]

**Review by stojkovicv — DISMISSED** [review]

**Review by jordijoangimenez — DISMISSED** [review]

**Review by jordijoangimenez — DISMISSED** [review]

**Review by jordijoangimenez — DISMISSED** [review]

**Comment by davidjwbbc** [comment]
These "The merge-base changed after approval." messages and dismissing "stale" reviews seem to be being made automatically by GitHub. I'm going to bypass the rules and merge anyway.

**Pull request merged**
